# core/generation_log.py
# Generation log creation and management

"""
Generation Log module for Project Foundation Template.

Tracks auto-generated files, their sources, and customizations.
Supports markdown and JSON output formats.

WHAT: A log file documenting which files were generated and when.
WHY: Provides transparency about file provenance and enables
     tracking of customizations over time.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

from core.utils import SCRIPT_VERSION


def generate_log_md(
    project_name: str,
    files: List[Dict[str, Any]],
    existing_content: Optional[str] = None
) -> str:
    """
    Generate GENERATION_LOG.md content in markdown format.

    Args:
        project_name: Name of the project
        files: List of generated file records
        existing_content: Content from existing log to append to

    Returns:
        Markdown-formatted generation log
    """
    if existing_content:
        # Append new entries to existing log
        lines = existing_content.rstrip().split('\n')

        # Find the table and append new rows
        new_rows = []
        for f in files:
            new_rows.append(
                f"| {f['file']} | {f['generated']} | {f['tool']} | "
                f"{f['tool_version']} | {f.get('customization', '-')} |"
            )

        # Append new rows before any closing content
        return existing_content.rstrip() + '\n' + '\n'.join(new_rows) + '\n'

    # Create new log
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = f"""# Generation Log

Tracks auto-generated files, their sources, and customizations.

**Project**: {project_name}
**Last Updated**: {timestamp}

## Generated Files

| File | Generated | Tool | Version | Customization |
|------|-----------|------|---------|---------------|
"""

    for f in files:
        content += (
            f"| {f['file']} | {f['generated']} | {f['tool']} | "
            f"{f['tool_version']} | {f.get('customization', '-')} |\n"
        )

    content += """
## Understanding This Log

This log provides transparency about auto-generated files in your project.

**Columns explained**:
- **File**: Path to the generated file
- **Generated**: Date the file was created or regenerated
- **Tool**: The tool that generated the file
- **Version**: Version of the tool used
- **Customization**: Summary of modifications made after generation

**Usage**:
- Update the Customization column when you modify generated files
- Re-run the generator with `--log-to GENERATION_LOG.md` to append new entries
- Review before upgrades to understand what might change

---

*This file was generated by [Project Foundation Template](https://github.com/malcolmhoward/project-foundation-template)*
"""

    return content


def generate_log_json(
    project_name: str,
    files: List[Dict[str, Any]],
    existing_content: Optional[str] = None
) -> str:
    """
    Generate GENERATION_LOG.json content.

    Args:
        project_name: Name of the project
        files: List of generated file records
        existing_content: Content from existing log to merge with

    Returns:
        JSON-formatted generation log
    """
    timestamp = datetime.now().isoformat()

    if existing_content:
        try:
            existing = json.loads(existing_content)
            # Append new files to existing log
            existing['files'].extend(files)
            existing['last_updated'] = timestamp
            return json.dumps(existing, indent=2)
        except json.JSONDecodeError:
            # If existing content is invalid, create new
            pass

    log_data = {
        "version": "1.0",
        "project": project_name,
        "generated": timestamp,
        "last_updated": timestamp,
        "tool": "Project Foundation Template",
        "tool_version": SCRIPT_VERSION,
        "files": files
    }

    return json.dumps(log_data, indent=2)


def create_file_record(
    filepath: str,
    tool: str = "PFT",
    customization: str = "-"
) -> Dict[str, Any]:
    """
    Create a file record for the generation log.

    Args:
        filepath: Path to the generated file
        tool: Tool that generated the file (default: PFT)
        customization: Description of customizations (default: -)

    Returns:
        Dictionary with file record data
    """
    return {
        "file": filepath,
        "generated": datetime.now().strftime("%Y-%m-%d"),
        "tool": tool,
        "tool_version": SCRIPT_VERSION,
        "customization": customization
    }


def load_existing_log(log_path: Path, format: str = "md") -> Optional[str]:
    """
    Load existing generation log content.

    Args:
        log_path: Path to existing log file
        format: Format of the log (md or json)

    Returns:
        Content of existing log, or None if not found
    """
    if not log_path.exists():
        return None

    try:
        with open(log_path, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception:
        return None


def write_generation_log(
    output_dir: Path,
    project_name: str,
    generated_files: List[str],
    log_format: str = "md",
    log_to: Optional[str] = None
) -> List[str]:
    """
    Write generation log files based on format option.

    Args:
        output_dir: Directory to write log files to
        project_name: Name of the project
        generated_files: List of file paths that were generated
        log_format: Format option (md, json, or both)
        log_to: Path to existing log to append to

    Returns:
        List of log files created
    """
    # Create file records for all generated files
    files = [create_file_record(f) for f in generated_files]

    created_logs = []

    # Handle appending to existing log
    existing_md = None
    existing_json = None

    if log_to:
        log_path = Path(log_to)
        if log_path.suffix == '.json':
            existing_json = load_existing_log(log_path, "json")
        else:
            existing_md = load_existing_log(log_path, "md")

    # Generate markdown log
    if log_format in ("md", "both"):
        md_content = generate_log_md(project_name, files, existing_md)
        md_path = output_dir / "GENERATION_LOG.md"

        if log_to and not log_to.endswith('.json'):
            md_path = Path(log_to)

        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        created_logs.append(str(md_path))

    # Generate JSON log
    if log_format in ("json", "both"):
        json_content = generate_log_json(project_name, files, existing_json)
        json_path = output_dir / "GENERATION_LOG.json"

        if log_to and log_to.endswith('.json'):
            json_path = Path(log_to)

        with open(json_path, 'w', encoding='utf-8') as f:
            f.write(json_content)
        created_logs.append(str(json_path))

    return created_logs
