# foundation/templates/core.py
# Core template generators: README, CONTRIBUTING, LICENSE, .gitignore

"""
Core templates for Project Foundation Template.

Contains template generators for:
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    - .gitignore
"""

from datetime import date
from core.utils import SCRIPT_VERSION, OFFICIAL_REPO


def generate_readme_content(project_name: str, license_type: str) -> str:
    """Generate README.md content with educational comments."""
    return f"""# {project_name}

<!--
TEMPLATE NOTICE: This is a starting point. Replace all placeholder text.
Generated by: {SCRIPT_VERSION} on {date.today().isoformat()}
Remember: This template does not make your project secure or compliant.
-->

## Description

[REPLACE: Describe what your project does and why it exists]

## Why This Project?

[REPLACE: What problem does this solve? Why should someone care?]

## Quick Start

```bash
# Installation
[REPLACE: How to install your project]

# Basic usage
[REPLACE: Simplest possible example]
```

## Documentation

[REPLACE: Link to detailed documentation]

## Contributing

Please see [CONTRIBUTING.md](CONTRIBUTING.md) for guidelines.

<!-- LEARNING: Good READMEs include contribution info even if brief -->

## License

This project is licensed under the {license_type.upper()} License - see [LICENSE](LICENSE) file.

## Security

For security concerns, see [SECURITY.md](SECURITY.md).

<!-- LEARNING: Always provide a security contact method -->

## Important Notice

This README was generated from a template. It must be customized for your specific project.
Using template documentation without customization may mislead users and contributors.

---

Generated with [Project Foundation Generator]({OFFICIAL_REPO}) - Please customize!
"""


def generate_contributing_content(project_name: str) -> str:
    """Generate comprehensive CONTRIBUTING.md content with educational elements."""
    project_slug = project_name.lower().replace(' ', '-')
    return f"""# Contributing to {project_name}

<!--
TEMPLATE NOTICE: This is a comprehensive contribution guide template.
Customize sections marked with [CUSTOMIZE] for your project's specific needs.
-->

Thank you for your interest in contributing to {project_name}!

This guide explains our contribution workflow, conventions, and review process.

---

## Before You Start

### Understanding Our Workflow

We use a **fork-first workflow**. This means:
- You work on your own copy (fork) of the repository
- Changes are proposed via Pull Requests from your fork
- This keeps the main repository clean and secure

### Why Fork-First?

1. **Security**: Only maintainers have write access to the main repo
2. **Experimentation**: You can freely experiment in your fork
3. **Learning**: Great practice for contributing to any open source project
4. **Backup**: Your fork serves as a backup of your work

---

## Fork-First Workflow

### Step 1: Fork the Repository

1. Click the "Fork" button on the repository page
2. This creates your personal copy at `github.com/YOUR-USERNAME/{project_slug}`

### Step 2: Clone Your Fork

```bash
# Clone your fork locally
git clone https://github.com/YOUR-USERNAME/{project_slug}.git
cd {project_slug}

# Add the original repo as "upstream" for syncing
git remote add upstream https://github.com/ORIGINAL-OWNER/{project_slug}.git
```

### Step 3: Keep Your Fork Updated

```bash
# Fetch upstream changes
git fetch upstream

# Merge upstream main into your local main
git checkout main
git merge upstream/main

# Push updates to your fork
git push origin main
```

### Step 4: Create a Feature Branch

**Never work directly on `main`**. Always create a branch:

```bash
git checkout -b type/description
```

---

## Branch Naming Conventions

Use descriptive branch names following this pattern:

```
type/short-description
```

### Branch Types

| Type | Purpose | Example |
|------|---------|---------|
| `feat/` | New feature | `feat/user-authentication` |
| `fix/` | Bug fix | `fix/login-validation` |
| `docs/` | Documentation only | `docs/api-examples` |
| `refactor/` | Code restructuring | `refactor/database-layer` |
| `test/` | Adding/updating tests | `test/auth-unit-tests` |
| `chore/` | Maintenance tasks | `chore/update-dependencies` |

### Good Branch Names
- `feat/add-dark-mode`
- `fix/memory-leak-on-upload`
- `docs/installation-guide`

### Avoid
- `my-changes` (not descriptive)
- `fix` (too vague)
- `john-branch` (personal names)

---

## Conventional Commits

We follow [Conventional Commits](https://www.conventionalcommits.org/) for clear, consistent history.

### Format

```
type(scope): description

[optional body]

[optional footer]
```

### Commit Types

| Type | When to Use |
|------|-------------|
| `feat` | Adding new functionality |
| `fix` | Fixing a bug |
| `docs` | Documentation changes only |
| `style` | Formatting (no code logic change) |
| `refactor` | Restructuring without behavior change |
| `test` | Adding or updating tests |
| `chore` | Maintenance (dependencies, configs) |

### Examples

```bash
# Feature
git commit -m "feat(auth): add password reset flow"

# Bug fix
git commit -m "fix(api): handle null response from server"

# Documentation
git commit -m "docs(readme): add installation instructions"

# Breaking change (note the !)
git commit -m "feat(api)!: change authentication endpoint"
```

### Why Conventional Commits?

1. **Automatic changelogs**: Tools can generate release notes
2. **Clear history**: Easy to understand what changed and why
3. **Semantic versioning**: Commit types inform version bumps
4. **Better reviews**: Reviewers understand intent quickly

---

## Suggesting Features

### Before Proposing

1. **Search existing issues** - your idea may already be discussed
2. **Check the roadmap** - it might be planned already
3. **Consider scope** - does it fit the project's goals?

### Priority Assessment

When proposing features, consider these factors:

| Factor | Questions to Ask |
|--------|------------------|
| **Impact** | How many users benefit? How significant is the improvement? |
| **Effort** | How complex is implementation? What's the maintenance burden? |
| **Risk** | What could break? Are there security implications? |
| **Alignment** | Does it fit project goals and architecture? |

### Feature Request Template

```markdown
## Problem Statement
What problem does this solve?

## Proposed Solution
How should it work?

## Alternatives Considered
What other approaches exist?

## Priority Assessment
- Impact: [High/Medium/Low]
- Effort: [High/Medium/Low]
- Risk: [High/Medium/Low]
```

---

## Code Review Process

### What Reviewers Look For

1. **Correctness**: Does the code do what it claims?
2. **Tests**: Are changes covered by tests?
3. **Style**: Does it follow project conventions?
4. **Documentation**: Are changes documented?
5. **Security**: Are there any vulnerabilities?
6. **Performance**: Any performance implications?

### Educational Review Criteria

We review with education in mind:

| Criteria | What We Check |
|----------|---------------|
| **Clarity** | Is the code readable and self-documenting? |
| **Simplicity** | Is this the simplest solution that works? |
| **Maintainability** | Will future contributors understand this? |
| **Best Practices** | Does it follow established patterns? |

### Responding to Feedback

- **Be open**: Feedback improves code quality
- **Ask questions**: If something is unclear, ask
- **Iterate**: Multiple rounds of review are normal
- **Learn**: Each review is a learning opportunity

---

## Pull Request Process

### Before Submitting

- [ ] Code compiles/runs without errors
- [ ] Tests pass locally
- [ ] Branch is up-to-date with main
- [ ] Commit messages follow conventions
- [ ] Documentation updated if needed

### PR Description Template

```markdown
## Summary
Brief description of changes.

## Type of Change
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation
- [ ] Refactoring

## Testing
How were changes tested?

## Checklist
- [ ] Tests added/updated
- [ ] Documentation updated
- [ ] No breaking changes (or documented)
```

### After Submitting

1. **Respond to reviews** within a reasonable timeframe
2. **Push fixes** as new commits (easier to review)
3. **Request re-review** after addressing feedback
4. **Squash commits** will happen on merge (if configured)

---

## Coding Standards

[CUSTOMIZE: Add your project-specific coding standards here]

### General Guidelines

- Write clear, self-documenting code
- Include comments for complex logic
- Follow existing patterns in the codebase
- Keep functions focused and small

### Testing Requirements

[CUSTOMIZE: Specify your testing requirements]

- Unit tests for new functionality
- Integration tests for API changes
- All tests must pass before merge

---

## Code of Conduct

[CUSTOMIZE: Reference your CODE_OF_CONDUCT.md if you have one]

We are committed to providing a welcoming and inclusive environment.
Please be respectful and constructive in all interactions.

---

## Getting Help

- **Questions**: [CUSTOMIZE: Where should questions go?]
- **Bugs**: Open an issue with the bug report template
- **Features**: Open an issue with the feature request template

---

## Template Notice

This CONTRIBUTING.md was generated as a starting point.
Sections marked with [CUSTOMIZE] need project-specific content.
Review and adapt all sections to match your actual workflow.

---

Generated with [Project Foundation Template]({OFFICIAL_REPO})
"""


# License templates
LICENSE_TEMPLATES = {
    "mit": """MIT License

Copyright (c) {year} {author}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.""",

    "apache": """Copyright {year} {author}

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.""",

    "gpl": """This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Copyright (C) {year} {author}"""
}


def generate_license_content(license_type: str, author_name: str) -> str:
    """Generate LICENSE file content with explanation."""
    license_text = LICENSE_TEMPLATES.get(license_type, LICENSE_TEMPLATES["mit"])
    license_text = license_text.format(
        year=date.today().year,
        author=author_name
    )

    # Add educational header
    educational_header = f"""# LICENSE NOTICE

This is a TEMPLATE license. You must:
1. Verify this license suits your needs
2. Replace {{author}} with actual copyright holder
3. Consider patent, trademark, and other IP concerns
4. Consult legal counsel for commercial projects

License type: {license_type.upper()}
Learn more: https://choosealicense.com/licenses/{license_type}/

---

"""

    return educational_header + license_text


def generate_gitignore_content() -> str:
    """Generate .gitignore content."""
    return """# Dependencies
node_modules/
vendor/
venv/
env/

# Environment files
.env
.env.*
!.env.example

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db

# Build outputs
dist/
build/
*.pyc
__pycache__/

# Logs
*.log
logs/

# Testing
coverage/
.coverage
.pytest_cache/

# PFT usage logging (local accountability trail)
.project_foundation_logs/

# Project specific
# [ADD YOUR PROJECT'S SPECIFIC IGNORES HERE]
"""
