# foundation/templates/github.py
# GitHub template generators: Issue templates, PR template, workflows

"""
GitHub templates for Project Foundation Template.

Contains template generators for:
    - Bug report issue template
    - Feature request issue template
    - Pull request template
    - CI workflow
    - PR validation workflow
"""

from core.utils import OFFICIAL_REPO


def generate_bug_report_template() -> str:
    """Generate GitHub bug report issue template."""
    return f"""---
name: Bug Report
about: Create a report to help us improve
title: '[Bug]: '
labels: 'bug, triage'
assignees: ''
---

## Bug Description
<!-- A clear and concise description of what the bug is -->

## Steps to Reproduce
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

## Expected Behavior
<!-- What you expected to happen -->

## Actual Behavior
<!-- What actually happened -->

## Environment
- OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
- Version: [e.g., v1.0.0]
- Browser (if applicable): [e.g., Chrome 120]

## Screenshots
<!-- If applicable, add screenshots to help explain your problem -->

## Additional Context
<!-- Add any other context about the problem here -->

## Possible Solution
<!-- Optional: If you have a suggestion for fixing the bug -->

---
*Generated with [Project Foundation Template]({OFFICIAL_REPO})*
"""


def generate_feature_request_template() -> str:
    """Generate GitHub feature request issue template."""
    return f"""---
name: Feature Request
about: Suggest an idea for this project
title: '[Feature]: '
labels: 'enhancement'
assignees: ''
---

## Problem Statement
<!-- Is your feature request related to a problem? Describe it -->
<!-- Example: I'm always frustrated when... -->

## Proposed Solution
<!-- A clear and concise description of what you want to happen -->

## Alternatives Considered
<!-- Any alternative solutions or features you've considered -->

## Additional Context
<!-- Add any other context, mockups, or screenshots about the feature request -->

## Priority Assessment (Optional)
<!-- If you've evaluated this feature: -->
- **Impact**: How much does this improve the project?
- **Effort**: How realistic is implementation?
- **Risk**: What could go wrong?
- **Suggested Priority**: High / Medium / Low

---
*Generated with [Project Foundation Template]({OFFICIAL_REPO})*
"""


def generate_pr_template_content() -> str:
    """Generate GitHub pull request template."""
    return f"""## Description
<!-- Describe your changes in detail -->

## Related Issue
<!-- Link to the issue this PR addresses (e.g., Closes #123) -->

## Type of Change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Performance improvement
- [ ] Test updates

## Checklist
- [ ] My code follows the project's style guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Screenshots (if applicable)
<!-- Add screenshots to demonstrate the change -->

## Additional Notes
<!-- Any additional information that reviewers should know -->

---
*Generated with [Project Foundation Template]({OFFICIAL_REPO})*
"""


def generate_ci_workflow_content() -> str:
    """Generate GitHub Actions CI workflow."""
    # Using raw string and careful escaping for GitHub Actions syntax
    return """# Continuous Integration Workflow
# Generated by Project Foundation Template v2.6.0
#
# This workflow runs on every push and pull request to ensure code quality.
# Customize the steps below for your project's needs.

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # [CUSTOMIZE]: Update for your language/runtime versions
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # [CUSTOMIZE]: Replace with your language's setup action
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # [CUSTOMIZE]: Replace with your package manager commands
      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
        continue-on-error: true  # Remove this line once linting is configured

      - name: Run tests
        run: npm test
        continue-on-error: true  # Remove this line once tests are configured

      - name: Build
        run: npm run build
        continue-on-error: true  # Remove this line once build is configured

  # Optional: Add security scanning
  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run security audit
  #       run: npm audit

# ---
# TEMPLATE NOTICE:
# This is a starting point. You must:
# 1. Replace placeholder commands with your actual build/test commands
# 2. Update the matrix for your language versions
# 3. Remove continue-on-error once steps are properly configured
# 4. Add additional jobs as needed (deploy, security scan, etc.)
#
# Generated with Project Foundation Template
# https://github.com/malcolmhoward/project-foundation-template
"""


def generate_pr_validation_workflow_content() -> str:
    """Generate PR validation workflow for conventional commits."""
    return """# Pull Request Validation
# Validates PR title follows conventional commits format

name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Require conventional commit format
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          subjectPattern: ^.{1,50}$
          subjectPatternError: |
            PR title must be 50 characters or less.
            Current length: {length}

# ---
# This workflow ensures PR titles follow conventional commits format.
# This helps with automatic changelog generation and semantic versioning.
#
# Generated with Project Foundation Template
"""
